revise: implement membership cancellation mechanism (TS-461)
TakafulDAO/takasure.sc pull request #39
Opened 2024-08-28 00:44 UTC by maikelordaz

Here also applied defaulting a member as of previous conversations, done inside here because I'm using the `Defaulted` state for the cancellation implementation.

PS: While I'm writing this I saw the word `cancellation` with two `L` but in the contract I wrote `Canceled` I looked in the web and I find that `Canceled` and `Cancelled` are both correct, so let me know which one to use

2025-01-19 00:24 UTC, elallamTaka requested changes

2025-01-19 00:24 UTC, elallamTaka commented on contracts/takasure/TakasurePool.sol
> +            emit TakasureEvents.OnMemberDefaulted(reserve.members[msg.sender].memberId, msg.sender);
Hey Maikel, i can see that if a user tries to make a payment after his grace days passing, then his state is updated to defaulted. This behavior is out of the concern of this function. Meaning, `recurringPayment ` must only focus on making the payment, and failing if its the wrong user state. Thus here you can simply return an error such as `paymentTooLate`. It will be the responsibility of the CS to mark the user as defaulted, or the responsibility of a cron job.

2025-01-19 00:24 UTC, elallamTaka commented on contracts/takasure/TakasurePool.sol
>      function recurringPayment() external {
Since this is an action the user takes, I suggest we follow the same naming convention of starting with the verb like what we did for `payContribution`. Maybe `payRecurringContribution` ?

2025-01-19 00:24 UTC, elallamTaka commented on contracts/takasure/TakasurePool.sol
> +                reserve.members[msg.sender].totalServiceFee
I dont think the total contribution here is required to be emitted. Rather, the frontend wants to display the contribution paid as a transaction so perhaps we can emit the same values emitted for the first payment.

2025-01-19 00:24 UTC, elallamTaka commented on contracts/takasure/TakasurePool.sol
> +        uint256 limitTimestamp = member.membershipStartTime + lastPaidYearStartDate + (30 days); // 30 days after the new membership year
This is a default, which means users default if they dont make the payment before the end of their membership year, so we must remove 30 days from here. 

To recap, if a user misses a payment, he defaults. If he fails to pay within 30 days (grace period) his membership gets cancelled.

2025-01-19 00:24 UTC, elallamTaka commented on contracts/takasure/TakasurePool.sol
> +    function _cancelMembership(
The cancellation is missing running some key algorithms such as distributing the surplus according to the cancellation year (based on the reqs). However I prefer we update it later after we do the optimization. I have created a backlog ticket for it.

2025-01-20 02:12 UTC, maikelordaz commented on contracts/takasure/TakasurePool.sol
>      function recurringPayment() external {
Commit e307311

2025-01-20 02:24 UTC, maikelordaz commented on contracts/takasure/TakasurePool.sol
> +                reserve.members[msg.sender].totalServiceFee
Commit 7d78560

2025-01-20 02:31 UTC, maikelordaz commented on contracts/takasure/TakasurePool.sol
> +        uint256 limitTimestamp = member.membershipStartTime + lastPaidYearStartDate + (30 days); // 30 days after the new membership year
Commit c18de38

2025-01-20 02:45 UTC, maikelordaz commented on contracts/takasure/TakasurePool.sol
> +            emit TakasureEvents.OnMemberDefaulted(reserve.members[msg.sender].memberId, msg.sender);
Commit a4d5b2c

2025-01-20 02:45 UTC, maikelordaz commented on contracts/takasure/TakasurePool.sol
> +    function _cancelMembership(
Got it

2025-01-24 23:50 UTC, elallamTaka approved these changes

2025-01-25 19:52 UTC, merged