revise: implement proposal process for upgrades (TS-924)
TakafulDAO/takasure.sc pull request #51
Opened 2024-11-22 03:54 UTC by maikelordaz

2024-11-27 06:15 UTC, elallamTaka requested changes

2024-11-27 06:15 UTC, elallamTaka commented on contracts/referrals/ReferralGateway.sol
should the constant Test be removed first before merging this PR?

2024-11-28 02:41 UTC, maikelordaz commented on contracts/referrals/ReferralGateway.sol
Removed it. Also added two scripts two change the corresponding roles

2024-11-28 02:43 UTC, maikelordaz commented on contracts/referrals/ReferralGateway.sol
I used this contract to test those scripts on chain https://sepolia.etherscan.io/address/0x567c3b31a85b6eb15d9fa3318c6521bf2454a7f1

2024-11-28 11:20 UTC, elallamTaka approved these changes

2024-11-28 12:10 UTC, merged